name: CI Pipeline
on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next
jobs:
  SimpleCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out repository code & install node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - name: Install
        run: "npm ci"
      - name: Build
        run: "npm run build:prod"
      - name: Lint
        run: npm run lint
      - name: Unit Test
        run: npm run test
